# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152E1X2bKqbNs-xbp8g3u2XTw8uf3oWPU
"""

import numpy as np
import pandas as pd
df = pd.read_csv("german.data-numeric", sep='\s+', header=None)
print(df.shape)
y=df.iloc[:,-1]
x=df.iloc[:,:-1]
# question 1
# function for entropy calculation
def entropy(colu):
  [values,counts]=np.unique(colu,return_counts=True)
  ent=0
  prob=counts/len(colu)
  for p in prob:
    ent-=p*np.log2(p)
  return float(ent)

h_s=entropy(y)
print(h_s)
entr_all_cols=[0  for i in range(x.shape[1])]
for i in range(x.shape[1]):
  entr_all_cols[i]=entropy(x.iloc[:,i])
print(entr_all_cols)

# question 2
def gini_index(col):
  [values,counts]=np.unique(col,return_counts=True)
  prob=counts/len(col)
  return 1-np.sum(prob**2)
gin_index=gini_index(y)
print(gin_index)

#question 3
def weights(df,feautur):
  [values,counts]=np.unique(df.iloc[:,feautur],return_counts=True)
  weigh_enr=0
  for value,c in zip(values,counts):
    sub_dataset=df[df.iloc[:,feautur]==value]
    entr=entropy(sub_dataset.iloc[:,-1])
    weigh_enr+=(c/len(df))*entr
  return weigh_enr
weigh_entopy=[]
for i in range(x.shape[1]):
  weigh_entopy.append(weights(df,i))
minvalue=h_s-weigh_entopy[0]
min_id=0
for i in range(1,x.shape[1]):
  ig=h_s-weigh_entopy[i]
  if(ig>minvalue):
    minvalue=ig
    min_id=i
print("column",min_id," can be selected as root node")