# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/152E1X2bKqbNs-xbp8g3u2XTw8uf3oWPU
"""

import pandas as pd
import numpy as np
import random
ar=np.array(np.random.randint(1,1000,size=1000))
print(ar.size)

def binning(ar,typ="equal",n_bins=4):
  arr=np.array(ar)
  if(typ=="equal"):
    n_elements=(np.max(ar)-np.min(ar))/n_bins
    m=np.min(ar)
    bins=[[] for i in range(n_bins)]
    for i in range(len(arr)):
      id=int((arr[i]-m)/n_elements)
      if(id==n_bins):
        id-=1
      bins[id].append(int(arr[i]))
    return bins
  if(typ=="frequency"):
    arr=np.sort(arr)
    l=arr.size
    idx=int(l/n_bins)
    bins=[]
    for i in range(n_bins):
      if(i==n_bins-1):
        bins.append(arr[i*idx:])
      else:
        bins.append(arr[i*idx:(i+1)*idx])

    return bins
bins=binning(ar,typ="equal",n_bins=4)
bins1=binning(ar,typ="frequency",n_bins=4)
print(bins)
print(bins1)